require('dotenv').config();
const express = require('express');
const cors = require('cors');
const path = require('path');
const fs = require('fs');
const { printZPL, buildWristbandZPL, buildLabelZPL } = require('./printer/zplService');

let oracledb;
try {
  oracledb = require('oracledb');
  if (process.env.ORACLE_CLIENT_LIB_DIR) {
    try { oracledb.initOracleClient({ libDir: process.env.ORACLE_CLIENT_LIB_DIR }); } catch (_) {}
  }
} catch (_) {
  console.log('[AVISO] Módulo oracledb não instalado. Usando base de leitos oficial com nomes únicos.');
}

const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

const PORT = process.env.PORT || 3011;
const EVENTOS_FILE = path.join(__dirname, 'eventos-leitos.json');

// ─── Persistência local de eventos/histórico ──────────────────────────────────
function readEventos() {
  if (!fs.existsSync(EVENTOS_FILE)) return { leitos: {}, historico: [] };
  try {
    const data = JSON.parse(fs.readFileSync(EVENTOS_FILE, 'utf-8'));
    if (!data.historico) data.historico = [];
    if (!data.leitos)    data.leitos    = {};
    return data;
  } catch {
    return { leitos: {}, historico: [] };
  }
}

function writeEventos(data) {
  fs.writeFileSync(EVENTOS_FILE, JSON.stringify(data, null, 2));
}

// ─── Resolver hospital pelo nome da unidade ───────────────────────────────────
function resolverHospital(unidade, cdMultiEmpresa) {
  if (cdMultiEmpresa == 2) return 'CMI';
  if (cdMultiEmpresa == 1) return 'HPRB';
  if (!unidade) return 'CMI';
  const u = String(unidade).toUpperCase();
  if (u.includes('CMI')) return 'CMI';
  if (u.includes('HPRB')) return 'HPRB';
  return 'CMI';
}

// ─── Consulta Oracle (Soul MV) — DADOS EM TEMPO REAL ─────────────────────────
async function fetchLeitosOracle() {
  if (!oracledb || !process.env.DB_USER || !process.env.DB_CONNECT_STRING) return null;

  let connection;
  try {
    connection = await oracledb.getConnection({
      user:          process.env.DB_USER,
      password:      process.env.DB_PASSWORD,
      connectString: process.env.DB_CONNECT_STRING
    });

    // Mesma query confirmada via SQLTools no ambiente do hospital
    const sql = `
      SELECT
        lei.cd_leito,
        lei.ds_leito                                      AS leito,
        unid.ds_unid_int                                  AS unidade,
        unid.cd_multi_empresa,
        a.cd_atendimento,
        TRIM(p.nm_paciente)                               AS nm_paciente,
        TO_CHAR(p.dt_nascimento, 'DD/MM/YYYY')            AS dt_nascimento,
        p.tp_sexo                                         AS sexo,
        NVL(lei.tp_ocupacao,
            CASE WHEN a.cd_atendimento IS NOT NULL
                 THEN 'O' ELSE 'L' END)                   AS st_leito_raw
      FROM dbamv.leito lei
      JOIN dbamv.unid_int unid ON lei.cd_unid_int = unid.cd_unid_int
      LEFT JOIN dbamv.atendime a
             ON lei.cd_leito = a.cd_leito
            AND a.dt_alta IS NULL
            AND a.tp_atendimento IN ('I','U','A')
      LEFT JOIN dbamv.paciente p ON a.cd_paciente = p.cd_paciente
      WHERE lei.sn_ativo = 'S'
      ORDER BY unid.ds_unid_int, lei.ds_leito
    `;

    const result = await connection.execute(sql, [], { outFormat: oracledb.OUT_FORMAT_OBJECT });

    return result.rows.map(r => {
      let st = 'livre';
      if (r.CD_ATENDIMENTO || r.ST_LEITO_RAW === 'O') st = 'ocupado';
      else if (r.ST_LEITO_RAW === 'H' || r.ST_LEITO_RAW === 'M') st = 'higienizacao';
      else if (r.ST_LEITO_RAW === 'R') st = 'reservado';

      return {
        cd_leito:       r.CD_LEITO,
        leito:          r.LEITO,
        unidade:        r.UNIDADE,
        hospital:       resolverHospital(r.UNIDADE, r.CD_MULTI_EMPRESA),
        cd_atendimento: r.CD_ATENDIMENTO  || null,
        nm_paciente:    r.NM_PACIENTE     || null,
        dt_nascimento:  r.DT_NASCIMENTO   || null,
        sexo:           r.SEXO            || null,
        status_leito:   st
      };
    });
  } catch (err) {
    console.error('[ERRO ORACLE]', err.message);
    return null;
  } finally {
    if (connection) try { await connection.close(); } catch (_) {}
  }
}

// ─── Pool de 500 nomes únicos para modo demonstração ─────────────────────────
// Nomes compostos típicos do Brasil — nenhum se repete
const NOMES_UNICOS = [
  'ADRIANA APARECIDA SOUZA','AILTON RIBEIRO DA SILVA','ALCIONE FERREIRA GOMES',
  'ALEXANDRE BORGES MELO','ALINE CRISTINA PEREIRA','ALINE SANTOS FIGUEIREDO',
  'AMANDA OLIVEIRA LIMA','ANA BEATRIZ ROCHA','ANA CARLA MOURA SANTOS',
  'ANA CLAUDIA FERREIRA','ANA FLAVIA RODRIGUES','ANA JULIA COSTA SILVA',
  'ANA PAULA NASCIMENTO','ANA RITA CUNHA SOUZA','ANDERSON LUIZ MARTINS',
  'ANDRE HENRIQUE PINTO','ANDREIA CRISTINA LOPES','ANTONIA MARIA ALVES',
  'ANTONIO FERREIRA LIMA','ANTONIO JOSE NUNES','ANTONIO MARCOS ROCHA',
  'APARECIDA MARIA COSTA','ARTUR HENRIQUE SILVA','BEATRIZ ALVES CARVALHO',
  'BEATRIZ LIMA FERREIRA','BENEDITA GOMES DA SILVA','BRUNA CAROLINA SOUZA',
  'BRUNA LETICIA ALVES','BRUNA RODRIGUES LIMA','BRUNELLA SILVA NASCIMENTO',
  'CARLOS ALBERTO FARIA','CARLOS AUGUSTO PEREIRA','CARLOS EDUARDO GOMES',
  'CARLOS HENRIQUE LIMA','CARLOS ROBERTO SOUSA','CAROLINA SILVA CAMPOS',
  'CASSIA APARECIDA LIMA','CATARINA ALVES SOUZA','CECILIA MARIA COSTA',
  'CELSO AUGUSTO NEVES','CICERA MARIA SANTOS','CILENE FERREIRA ALVES',
  'CLAUDIA APARECIDA ROCHA','CLAUDIA CRISTINA LIMA','CLAUDIA MARIA SOUSA',
  'CLAUDIA RODRIGUES SILVA','CLAUDINEIA GOMES SANTOS','CLEIDE APARECIDA LIMA',
  'CLEONICE MARIA SILVA','CRISTIANE FERREIRA ROCHA','CRISTIANE LIMA SOUZA',
  'CRISTIANO AUGUSTO NEVES','CRISTIANO SILVA MELO','DAIANE APARECIDA SANTOS',
  'DANIELA CRISTINA LIMA','DANIELA FERREIRA SOUSA','DANIELA RODRIGUES ALVES',
  'DANIELE CRISTINA SILVA','DANIELE SANTOS ROCHA','DANILO HENRIQUE GOMES',
  'DEISE APARECIDA LIMA','DENISE FERREIRA SOUZA','DIANA CRISTINA ALVES',
  'DIEGO HENRIQUE LIMA','DIEGO RODRIGUES SILVA','DILMA APARECIDA GOMES',
  'EDNA CRISTINA FERREIRA','EDNA MARIA LIMA','EDNA SOUZA ROCHA',
  'EDUARDO AUGUSTO NEVES','EDUARDO HENRIQUE SILVA','ELAINE APARECIDA LIMA',
  'ELAINE CRISTINA ROCHA','ELIANA FERREIRA SOUZA','ELIANE CRISTINA ALVES',
  'ELIANE MARIA LIMA','ELIAS HENRIQUE GOMES','ELIETE APARECIDA SILVA',
  'ELISABETE FERREIRA LIMA','ELISA RODRIGUES SOUZA','ELIZABETH CRISTINA ALVES',
  'ELOISA MARIA GOMES','ELZA APARECIDA SILVA','EMILIA FERREIRA LIMA',
  'EMILIO AUGUSTO ROCHA','ENILDO HENRIQUE NEVES','ERICA CRISTINA SILVA',
  'ERICA FERREIRA LIMA','ERICA RODRIGUES SOUZA','ESTER CRISTINA ALVES',
  'EUNICE APARECIDA GOMES','FABIANA CRISTINA LIMA','FABIANE FERREIRA SILVA',
  'FABIO AUGUSTO ROCHA','FABIO HENRIQUE NEVES','FABIO RODRIGUES SOUZA',
  'FATIMA APARECIDA ALVES','FATIMA CRISTINA LIMA','FERNANDA AUGUSTO SILVA',
  'FERNANDA CRISTINA ROCHA','FERNANDA FERREIRA LIMA','FERNANDA RODRIGUES SOUZA',
  'FERNANDO AUGUSTO NEVES','FERNANDO CRISTINA ALVES','FILIPE HENRIQUE GOMES',
  'FLAVIA APARECIDA SILVA','FLAVIA CRISTINA LIMA','FLAVIA FERREIRA ROCHA',
  'FLAVIO AUGUSTO NEVES','FLAVIO HENRIQUE SOUZA','FRANCINEIDE SILVA GOMES',
  'FRANCISCA LIMA ROCHA','GABRIEL AUGUSTO ALVES','GABRIELA CRISTINA LIMA',
  'GABRIELA FERREIRA SILVA','GABRIELE RODRIGUES SOUZA','GERALDO AUGUSTO NEVES',
  'GERALDO HENRIQUE ALVES','GILBERTO CRISTINA GOMES','GILDA APARECIDA SILVA',
  'GISELE FERREIRA LIMA','GISELE RODRIGUES ROCHA','GUSTAVO AUGUSTO NEVES',
  'GUSTAVO HENRIQUE SOUZA','HELENA APARECIDA ALVES','HELENA CRISTINA GOMES',
  'HELIO FERREIRA SILVA','HELOISA RODRIGUES LIMA','HENRIQUE AUGUSTO ROCHA',
  'HILDA APARECIDA NEVES','HORACIO HENRIQUE SOUZA','IGOR AUGUSTO ALVES',
  'ILZA CRISTINA GOMES','INES APARECIDA SILVA','INGRID FERREIRA LIMA',
  'IRENE RODRIGUES ROCHA','IRINA AUGUSTO NEVES','ISADORA HENRIQUE SOUZA',
  'ISABELA CRISTINA ALVES','ISABELA FERREIRA GOMES','ISABELA RODRIGUES SILVA',
  'IZABEL APARECIDA LIMA','JANAINA FERREIRA ROCHA','JANDIRA AUGUSTO NEVES',
  'JANETE HENRIQUE SOUZA','JAQUELINE CRISTINA ALVES','JAQUELINE FERREIRA GOMES',
  'JAQUELINE RODRIGUES SILVA','JESSICA APARECIDA LIMA','JESSICA CRISTINA ROCHA',
  'JESSICA FERREIRA NEVES','JOANA RODRIGUES SOUZA','JOAO CARLOS ALVES',
  'JOAO CARLOS GOMES','JOAO PEDRO SILVA','JONAS AUGUSTO LIMA',
  'JONATAN CRISTINA ROCHA','JORGE HENRIQUE NEVES','JOSE AUGUSTO SOUZA',
  'JOSE CARLOS ALVES','JOSE CARLOS GOMES','JOSE CLAUDIO SILVA',
  'JOSE HENRIQUE LIMA','JOSE LUIZ ROCHA','JOSEFA APARECIDA NEVES',
  'JOSEFINA CRISTINA SOUZA','JOSIANE FERREIRA ALVES','JOVITA RODRIGUES GOMES',
  'JULIA APARECIDA SILVA','JULIA CRISTINA LIMA','JULIANA FERREIRA ROCHA',
  'JULIANA RODRIGUES NEVES','JULIANO AUGUSTO SOUZA','JULIO HENRIQUE ALVES',
  'KAREN CRISTINA GOMES','KARLA FERREIRA SILVA','KATIA APARECIDA LIMA',
  'KATIA CRISTINA ROCHA','KELLY RODRIGUES NEVES','KENIA AUGUSTO SOUZA',
  'LARISSA CRISTINA ALVES','LARISSA FERREIRA GOMES','LAURA RODRIGUES SILVA',
  'LAVINIA APARECIDA LIMA','LEANDRO AUGUSTO ROCHA','LEANDRO HENRIQUE NEVES',
  'LEIA CRISTINA SOUZA','LEILIANE FERREIRA ALVES','LENA RODRIGUES GOMES',
  'LETICIA APARECIDA SILVA','LETICIA CRISTINA LIMA','LIDIA FERREIRA ROCHA',
  'LILIAN RODRIGUES NEVES','LILIANE AUGUSTO SOUZA','LINDALVA HENRIQUE ALVES',
  'LOURDES CRISTINA GOMES','LUCIA FERREIRA SILVA','LUCIANA APARECIDA LIMA',
  'LUCIANA CRISTINA ROCHA','LUCIANO RODRIGUES NEVES','LUIZ AUGUSTO SOUZA',
  'LUIZ CARLOS ALVES','LUIZ CARLOS GOMES','LUIZ HENRIQUE SILVA',
  'LUIZA APARECIDA LIMA','LUIZA CRISTINA ROCHA','MADALENA FERREIRA NEVES',
  'MAIRA RODRIGUES SOUZA','MANUELA AUGUSTO ALVES','MARCELA CRISTINA GOMES',
  'MARCELE FERREIRA SILVA','MARCELO APARECIDA LIMA','MARCELO AUGUSTO ROCHA',
  'MARCIA CRISTINA NEVES','MARCIA FERREIRA SOUZA','MARCIO RODRIGUES ALVES',
  'MARCO AUGUSTO GOMES','MARCOS CRISTINA SILVA','MARGARETE APARECIDA LIMA',
  'MARIA ALICE ROCHA','MARIA ALICE SANTOS','MARIA APARECIDA OLIVEIRA',
  'MARIA CECILIA SILVA','MARIA CLAUDIA FERREIRA','MARIA CRISTINA LIMA',
  'MARIA DE FATIMA GOMES','MARIA ELENA RODRIGUES','MARIA FERNANDA COSTA',
  'MARIA GABRIELA ALVES','MARIA HELENA SOUZA','MARIA INES MARTINS',
  'MARIA JOSE PEREIRA','MARIA LUCIA SANTOS','MARIA LUIZA FERREIRA',
  'MARIA NILDA ROCHA','MARINA AUGUSTO GOMES','MARINEIDE FERREIRA SILVA',
  'MARIO APARECIDA LIMA','MARIO AUGUSTO ROCHA','MARIO HENRIQUE NEVES',
  'MARLENE CRISTINA SOUZA','MARLI FERREIRA ALVES','MAURA RODRIGUES GOMES',
  'MAURICIO AUGUSTO SILVA','MAURO CRISTINA LIMA','MAYARA FERREIRA ROCHA',
  'MEIRE RODRIGUES NEVES','MICHELI AUGUSTO SOUZA','MICHELINE CRISTINA ALVES',
  'MIRIAM FERREIRA GOMES','MIRIAM RODRIGUES SILVA','MONIQUE APARECIDA LIMA',
  'MONICA CRISTINA ROCHA','NADIA FERREIRA NEVES','NATALIA RODRIGUES SOUZA',
  'NATANIEL AUGUSTO ALVES','NEUSA CRISTINA GOMES','NILZA FERREIRA SILVA',
  'NOEMIA APARECIDA LIMA','NUBIA AUGUSTO ROCHA','ODETE HENRIQUE NEVES',
  'OLGA CRISTINA SOUZA','OLIMPIA FERREIRA ALVES','PATRICIA RODRIGUES GOMES',
  'PATRICIA APARECIDA SILVA','PATRICIA AUGUSTO LIMA','PAULA CRISTINA ROCHA',
  'PAULO FERREIRA NEVES','PAULO RODRIGUES SOUZA','PEDRO AUGUSTO ALVES',
  'PEDRO HENRIQUE GOMES','PRISCILA APARECIDA SILVA','PRISCILA CRISTINA LIMA',
  'PRISCILA FERREIRA ROCHA','RACHEL RODRIGUES NEVES','RAFAELA AUGUSTO SOUZA',
  'RAMONA CRISTINA ALVES','RAQUEL FERREIRA GOMES','REBECA RODRIGUES SILVA',
  'REGIANE APARECIDA LIMA','REGINA CRISTINA ROCHA','RENATA FERREIRA NEVES',
  'RENATO RODRIGUES SOUZA','RITA DE CASSIA ALVES','RITA FERREIRA GOMES',
  'ROBERTA RODRIGUES SILVA','ROBERTO APARECIDA LIMA','ROBERTO AUGUSTO ROCHA',
  'RODRIGO CRISTINA NEVES','RODRIGO FERREIRA SOUZA','ROSANA RODRIGUES ALVES',
  'ROSANGELA APARECIDA GOMES','ROSANGELA CRISTINA SILVA','ROSELI FERREIRA LIMA',
  'ROSELI RODRIGUES ROCHA','ROSEMEIRE AUGUSTO NEVES','ROSIMARA CRISTINA SOUZA',
  'ROSIMEIRE FERREIRA ALVES','ROSIMERI RODRIGUES GOMES','SANDRA APARECIDA SILVA',
  'SANDRA CRISTINA LIMA','SANDRA FERREIRA ROCHA','SELMA RODRIGUES NEVES',
  'SERGIO AUGUSTO SOUZA','SILMARA CRISTINA ALVES','SILVIA FERREIRA GOMES',
  'SIMONE RODRIGUES SILVA','SIMONI APARECIDA LIMA','SIRLENE CRISTINA ROCHA',
  'SOLANGE FERREIRA NEVES','SONIA RODRIGUES SOUZA','SUELI AUGUSTO ALVES',
  'SUSANA CRISTINA GOMES','SUZANA FERREIRA SILVA','TATIANA APARECIDA LIMA',
  'TATIANE CRISTINA ROCHA','TELMA FERREIRA NEVES','TEREZA RODRIGUES SOUZA',
  'THALITA AUGUSTO ALVES','THIAGO CRISTINA GOMES','THUANE FERREIRA SILVA',
  'VANIA APARECIDA LIMA','VANUSA CRISTINA ROCHA','VERA FERREIRA NEVES',
  'VERONICA RODRIGUES SOUZA','VILMA AUGUSTO ALVES','VIRGINIA CRISTINA GOMES',
  'VIVIANE FERREIRA SILVA','VIVIANE APARECIDA LIMA','WAGNER CRISTINA ROCHA',
  'WANDA FERREIRA NEVES','WELLINGTON RODRIGUES SOUZA','WILMA AUGUSTO ALVES',
  'WILSON CRISTINA GOMES','ZENAIDE FERREIRA SILVA','ZILMA APARECIDA LIMA',
  'ZORAIDE CRISTINA ROCHA','ZULEIDE FERREIRA NEVES','ZULMA RODRIGUES SOUZA',
  'ADALGISA COSTA MELO','ADAUTO LIMA FARIA','ADELINA ROCHA BORGES',
  'ADILSON NEVES CAMPOS','ADRIANO SOUZA TEIXEIRA','AFONSO ALVES VIANA',
  'AGOSTINHO GOMES BRAGA','ALBERTINA SILVA FREITAS','ALCEU LIMA MONTEIRO',
  'ALCIDES ROCHA PIRES','ALDENIR NEVES MACEDO','ALDEVINA SOUZA QUEIROZ',
  'ALFREDO ALVES AGUIAR','ALICE GOMES MORAES','ALICIO SILVA CAVALCANTE',
  'ALMIRA LIMA BRITO','ALONSO ROCHA RIBEIRO','ALTAMIRO NEVES ANDRADE',
  'ALVANIR SOUZA CARVALHO','ALZIRA ALVES VIEIRA','AMELIA GOMES MOREIRA',
  'AMERICO SILVA ARAUJO','AMINTAS LIMA MENDES','AMIRA ROCHA PINHEIRO',
  'ANACLETO NEVES CUNHA','ANAIR SOUZA BASTOS','ANISIA ALVES COELHO',
  'APOLONIA GOMES LEAL','AQUILES SILVA AZEVEDO','ARABELA LIMA XAVIER',
  'ARCANGELO ROCHA CORREIA','ARCENIO NEVES LACERDA','ARDILES SOUZA GUIMARAES',
  'ARISTIDES ALVES MAGALHAES','ARLETE GOMES FONSECA','ARMELINDO SILVA PRADO',
  'ARNALDO LIMA BARBOSA','ARSENIO ROCHA TAVARES','ARTHUR NEVES GODOI',
  'ARTEMIA SOUZA SANTOS','ARYANE ALVES FERREIRA','ASCENSO GOMES CARDOSO',
  'ASSIS SILVA LEITE','ASSUNTA LIMA DUARTE','ASTOLFO ROCHA MIRANDA',
  'ASTERIO NEVES BATISTA','ATALIBA SOUZA RAMOS','ATILA ALVES CASTRO',
  'AUGUSTO GOMES DIAS','AUREA SILVA MELLO','AURELIO LIMA BECKER',
  'AUSTREGEZILO ROCHA ESTEVES','AVELINO NEVES RODRIGUES','AVENICIO SOUZA SILVA',
  'AZALEIA ALVES GOMES','AZARIAS GOMES FERREIRA','BALDOINO SILVA SANTOS',
  'BALBINO LIMA OLIVEIRA','BALBINA ROCHA ALVES','BALTAZAR NEVES LIMA',
  'BARBARA SOUZA ROCHA','BASILEO ALVES NEVES','BASILIO GOMES SOUZA',
  'BELARMINO SILVA ALVES','BELMIRA LIMA GOMES','BENIGNA ROCHA FERREIRA',
  'BENICIO NEVES SANTOS','BENTO SOUZA OLIVEIRA','BENVINDA ALVES LIMA',
  'BERENICE GOMES ROCHA','BERNARDO SILVA NEVES','BEVILAQUA LIMA SOUZA',
  'BIANCA ROCHA ALVES','BOLIVAR NEVES GOMES','BONIFACIO SOUZA FERREIRA',
  'BRAULIO ALVES SANTOS','BRENO GOMES OLIVEIRA','BRIGIDA SILVA LIMA',
  'BRISIDA ROCHA NEVES','BRITES NEVES SOUZA','CAETANO ALVES GOMES',
  'CALIXTO GOMES FERREIRA','CANDIDA SILVA SANTOS','CANINDE LIMA OLIVEIRA',
  'CARIDADE ROCHA ALVES','CARLINHOS NEVES GOMES','CARMEM SOUZA FERREIRA',
  'CARMELITA ALVES SANTOS','CARMELIA GOMES OLIVEIRA','CARMEM SILVA LIMA',
  'CARMINE ROCHA NEVES','CASIMIRA NEVES SOUZA','CASSILDA ALVES GOMES',
  'CASTELO GOMES FERREIRA','CAVALHEIRO SILVA SANTOS','CELESTINO LIMA OLIVEIRA',
  'CELINA ROCHA ALVES','CELSO NEVES GOMES','CENIRA SOUZA FERREIRA',
  'CERANTOLA ALVES SANTOS','CESARIA GOMES OLIVEIRA','CESARIO SILVA LIMA',
  'CICERO ROCHA NEVES','CIDINEI NEVES SOUZA','CILENE ALVES GOMES',
  'CINTIA GOMES FERREIRA','CIRINO SILVA SANTOS','CLAUDEMIRO LIMA OLIVEIRA'
];

// ─── Matriz completa dos leitos reais do CMI (banco de dados oficial) ─────────
const LEITOS_REAIS_CMI_RAW = [
  // CMI - ALOJAMENTO CONJ E GAR 5º
  [1651,'AC-501-01 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2307,'AC-501-01 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2306,'AC-501-01 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1652,'AC-501-02 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2354,'AC-501-02 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2309,'AC-501-02 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [2310,'AC-501-03 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2308,'AC-501-03 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[1653,'AC-501-03 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1656,'AC-501-04 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2353,'AC-501-04 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2311,'AC-501-04 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [2351,'AC-502-01 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[1674,'AC-502-01 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[1675,'AC-502-01 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [2366,'AC-502-02 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2314,'AC-502-02 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2315,'AC-502-02 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1655,'AC-502-03 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2317,'AC-502-03 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2316,'AC-502-03 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1657,'AC-502-04 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2318,'AC-502-04 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2319,'AC-502-04 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1658,'AC-503-01 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2320,'AC-503-01 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2321,'AC-503-01 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1659,'AC-503-02 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2328,'AC-503-02 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2323,'AC-503-02 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1672,'AC-503-03 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2322,'AC-503-03 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2325,'AC-503-03 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [2324,'AC-503-04 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2326,'AC-503-04 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2370,'AC-503-04 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1661,'AC-504-01 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2329,'AC-504-01 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2372,'AC-504-01 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1662,'AC-504-02 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[1663,'AC-504-02 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2331,'AC-504-02 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [2330,'AC-504-03 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2332,'AC-504-03 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2333,'AC-504-03 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1664,'AC-504-04 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2334,'AC-504-04 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2335,'AC-504-04 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1665,'AC-505-01 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2337,'AC-505-01 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2336,'AC-505-01 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1666,'AC-505-02 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2352,'AC-505-02 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2339,'AC-505-02 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1677,'AC-509 M ISO','CMI - ALOJAMENTO CONJ E GAR 5º'],[2364,'AC-509 RG ISO','CMI - ALOJAMENTO CONJ E GAR 5º'],[2371,'AC-509 RGN ISO','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [2375,'EXTRA4','CMI - ALOJAMENTO CONJ E GAR 5º'],[2365,'EXTRA5','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1667,'GAR-505-03 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2327,'GAR-505-03 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2369,'GAR-505-03 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1678,'GAR-505-04 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[1660,'GAR-505-04 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[1679,'GAR-505-04 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1670,'GAR-506-01 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2344,'GAR-506-01 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2346,'GAR-506-01 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [2341,'GAR-506-02 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2338,'GAR-506-02 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2340,'GAR-506-02 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [2374,'GAR-506-03 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[1668,'GAR-506-03 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[1680,'GAR-506-03 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [2343,'GAR-506-04 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2367,'GAR-506-04 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2363,'GAR-506-04 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1673,'GAR-507-01 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2347,'GAR-507-01 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2350,'GAR-507-01 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1676,'GAR-507-02 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2349,'GAR-507-02 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2373,'GAR-507-02 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1669,'GAR-507-03 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2345,'GAR-507-03 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2342,'GAR-507-03 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1671,'GAR-507-04 M','CMI - ALOJAMENTO CONJ E GAR 5º'],[2313,'GAR-507-04 RN','CMI - ALOJAMENTO CONJ E GAR 5º'],[2348,'GAR-507-04 RNG','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [1654,'GAR-508 M ISO','CMI - ALOJAMENTO CONJ E GAR 5º'],[2368,'GAR-508 RG ISO','CMI - ALOJAMENTO CONJ E GAR 5º'],[2312,'GAR-508 RN ISO','CMI - ALOJAMENTO CONJ E GAR 5º'],
  [2234,'INTER EXTRA01','CMI - ALOJAMENTO CONJ E GAR 5º'],
  // CMI - ALOJAMENTO CONJUNTO 4º
  [2217,'407-04 RN','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2000,'AC 401 01 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2001,'AC 401 01 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2153,'AC 401 01 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2002,'AC 401 02 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2154,'AC 401 02 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2008,'AC 401 02 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2004,'AC 401 03 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2155,'AC 401 03 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2005,'AC 401 03 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2051,'AC 401 04 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2052,'AC 401 04 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2156,'AC 401 04 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2007,'AC 402 01 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2355,'AC 402 01 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2157,'AC 402 01 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2010,'AC 402 02 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2011,'AC 402 02 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2158,'AC 402 02 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2012,'AC 402 03 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2013,'AC 402 03 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2159,'AC 402 03 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2014,'AC 402 04 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2160,'AC 402 04 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2015,'AC 402 04 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2016,'AC 403 01 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2017,'AC 403 01 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2161,'AC 403 01 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2032,'AC 403 02 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2019,'AC 403 02 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2162,'AC 403 02 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2020,'AC 403 03 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2021,'AC 403 03 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2163,'AC 403 03 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2022,'AC 403 04 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2023,'AC 403 04 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2164,'AC 403 04 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2024,'AC 404 01 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2025,'AC 404 01 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2165,'AC 404 01 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2026,'AC 404 02 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2027,'AC 404 02 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2166,'AC 404 02 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2028,'AC 404 03 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2029,'AC 404 03 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2224,'AC 404 03 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2167,'AC 404 04 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2003,'AC 404 04 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2030,'AC 404 04 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2040,'AC 405 01 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2168,'AC 405 01 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2031,'AC 405 01 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2042,'AC 405 02 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2169,'AC 405 02 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2043,'AC 405 02 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2044,'AC 405 03 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2170,'AC 405 03 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2041,'AC 405 03 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2046,'AC 405 04 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2045,'AC 405 04 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2171,'AC 405 04 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2055,'AC 406 01 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2172,'AC 406 01 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2047,'AC 406 01 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2034,'AC 406 02 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2179,'AC 406 02 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2033,'AC 406 02 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2036,'AC 406 03 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2174,'AC 406 03 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2035,'AC 406 03 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2037,'AC 406 04 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2175,'AC 406 04 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2009,'AC 406 04 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2038,'AC 407 01 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2176,'AC 407 01 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2039,'AC 407 01 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2049,'AC 407 02 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2177,'AC 407 02 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2048,'AC 407 02 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2006,'AC 407 03 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2178,'AC 407 03 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2050,'AC 407 03 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2053,'AC 407 04 M','CMI - ALOJAMENTO CONJUNTO 4º'],[2180,'AC 407 04 RNG','CMI - ALOJAMENTO CONJUNTO 4º'],[2173,'AC 407-04 RN','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2233,'AC 408 01 M ISO','CMI - ALOJAMENTO CONJUNTO 4º'],[2219,'AC 408 01 RN ISO','CMI - ALOJAMENTO CONJUNTO 4º'],[2054,'AC 408 01 RNG ISO','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2056,'AC 409 M ISO','CMI - ALOJAMENTO CONJUNTO 4º'],[2235,'AC 409 RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2218,'AC 409 RNG ISO','CMI - ALOJAMENTO CONJUNTO 4º'],
  [2018,'AC 410 ISO RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2216,'AC 410 ISO RN','CMI - ALOJAMENTO CONJUNTO 4º'],[2110,'AC 410 ISOLADO','CMI - ALOJAMENTO CONJUNTO 4º'],
  // CMI - BLOCO OBSTETRICO
  [1876,'BO PP 01 01','CMI - BLOCO OBSTETRICO'],[1877,'BO PP 01 02','CMI - BLOCO OBSTETRICO'],[1878,'BO PP 01 03','CMI - BLOCO OBSTETRICO'],[1879,'BO PP 01 04','CMI - BLOCO OBSTETRICO'],
  [1880,'BO PP 02 05','CMI - BLOCO OBSTETRICO'],[1881,'BO PP 02 06','CMI - BLOCO OBSTETRICO'],[1882,'BO PP 02 07','CMI - BLOCO OBSTETRICO'],[1883,'BO PP 02 08','CMI - BLOCO OBSTETRICO'],
  [1885,'BO PP 03 09','CMI - BLOCO OBSTETRICO'],[1886,'BO PP 03 10','CMI - BLOCO OBSTETRICO'],[1902,'BO PP 03 11','CMI - BLOCO OBSTETRICO'],[1903,'BO PP 03 12','CMI - BLOCO OBSTETRICO'],
  [1904,'BO PP 04 13','CMI - BLOCO OBSTETRICO'],[1905,'BO PP 04 14','CMI - BLOCO OBSTETRICO'],[1906,'BO PP 04 15','CMI - BLOCO OBSTETRICO'],[1907,'BO PP 04 16','CMI - BLOCO OBSTETRICO'],
  [2097,'BO PP 05 17','CMI - BLOCO OBSTETRICO'],[2098,'BO PP 05 18','CMI - BLOCO OBSTETRICO'],[2099,'BO PP 05 19','CMI - BLOCO OBSTETRICO'],[2100,'BO PP 05 20','CMI - BLOCO OBSTETRICO'],
  [2130,'PP EX 01 BO','CMI - BLOCO OBSTETRICO'],[2131,'PP EX 02 BO','CMI - BLOCO OBSTETRICO'],[2132,'PP EX 03 BO','CMI - BLOCO OBSTETRICO'],[2133,'PP EX 04 BO','CMI - BLOCO OBSTETRICO'],[2134,'PP EX 05 BO','CMI - BLOCO OBSTETRICO'],
  [2081,'PP RN 01 01','CMI - BLOCO OBSTETRICO'],[2082,'PP RN 01 02','CMI - BLOCO OBSTETRICO'],[2083,'PP RN 01 03','CMI - BLOCO OBSTETRICO'],[2084,'PP RN 01 04','CMI - BLOCO OBSTETRICO'],
  [2085,'PP RN 02 05','CMI - BLOCO OBSTETRICO'],[2086,'PP RN 02 06','CMI - BLOCO OBSTETRICO'],[2087,'PP RN 02 07','CMI - BLOCO OBSTETRICO'],[2088,'PP RN 02 08','CMI - BLOCO OBSTETRICO'],
  [2089,'PP RN 03 09','CMI - BLOCO OBSTETRICO'],[2090,'PP RN 03 10','CMI - BLOCO OBSTETRICO'],[2091,'PP RN 03 11','CMI - BLOCO OBSTETRICO'],[2092,'PP RN 03 12','CMI - BLOCO OBSTETRICO'],
  [2093,'PP RN 04 13','CMI - BLOCO OBSTETRICO'],[2094,'PP RN 04 14','CMI - BLOCO OBSTETRICO'],[2095,'PP RN 04 15','CMI - BLOCO OBSTETRICO'],[2096,'PP RN 04 16','CMI - BLOCO OBSTETRICO'],
  [2101,'PP RN 05 17','CMI - BLOCO OBSTETRICO'],[2102,'PP RN 05 18','CMI - BLOCO OBSTETRICO'],[2103,'PP RN 05 19','CMI - BLOCO OBSTETRICO'],[2104,'PP RN 05 20','CMI - BLOCO OBSTETRICO'],
  // CMI - BO PRE PARTO
  [1884,'PRÉ PARTO 01 01','CMI - BO PRE PARTO'],[1887,'PRÉ PARTO 01 02','CMI - BO PRE PARTO'],[1888,'PRÉ PARTO 01 03','CMI - BO PRE PARTO'],[1889,'PRÉ PARTO 01 04','CMI - BO PRE PARTO'],
  [1890,'PRÉ PARTO 02 05','CMI - BO PRE PARTO'],[1891,'PRÉ PARTO 02 06','CMI - BO PRE PARTO'],[1892,'PRÉ PARTO 02 07','CMI - BO PRE PARTO'],[1893,'PRÉ PARTO 02 08','CMI - BO PRE PARTO'],
  [1894,'PRÉ PARTO 03 09','CMI - BO PRE PARTO'],[1895,'PRÉ PARTO 03 10','CMI - BO PRE PARTO'],[1896,'PRÉ PARTO 03 11','CMI - BO PRE PARTO'],[1897,'PRÉ PARTO 03 12','CMI - BO PRE PARTO'],
  [1898,'PRÉ PARTO 04 13','CMI - BO PRE PARTO'],[1899,'PRÉ PARTO 04 14','CMI - BO PRE PARTO'],[1900,'PRÉ PARTO 04 15','CMI - BO PRE PARTO'],[1901,'PRÉ PARTO 04 16','CMI - BO PRE PARTO'],
  [2227,'PRÉ PARTO 05 17','CMI - BO PRE PARTO'],[2228,'PRÉ PARTO 05 18','CMI - BO PRE PARTO'],
  // CMI - CENTRO DE PARTO NORMAL
  [1908,'BO-CPN01','CMI - CENTRO DE PARTO NORMAL'],[1909,'BO-CPN02','CMI - CENTRO DE PARTO NORMAL'],[1910,'BO-CPN03','CMI - CENTRO DE PARTO NORMAL'],
  [1911,'BO-CPN04','CMI - CENTRO DE PARTO NORMAL'],[1920,'BO-CPN05','CMI - CENTRO DE PARTO NORMAL'],
  [1913,'PP-CPN01F','CMI - CENTRO DE PARTO NORMAL'],[1914,'PP-CPN02F','CMI - CENTRO DE PARTO NORMAL'],[1915,'PP-CPN03F','CMI - CENTRO DE PARTO NORMAL'],
  [1916,'PP-CPN04F','CMI - CENTRO DE PARTO NORMAL'],[1921,'PP-CPN05F','CMI - CENTRO DE PARTO NORMAL'],
  [2229,'SRCPN01','CMI - CENTRO DE PARTO NORMAL'],[2230,'SRCPN02','CMI - CENTRO DE PARTO NORMAL'],[2231,'SRCPN03','CMI - CENTRO DE PARTO NORMAL'],[2232,'SRCPN04','CMI - CENTRO DE PARTO NORMAL'],
  // CMI - CIRURGIA GINECOLOGICA
  [1742,'CECOVID4-CTI06-606-17','CMI - CIRURGIA GINECOLOGICA'],[1743,'CECOVID4-CTI06-606-18','CMI - CIRURGIA GINECOLOGICA'],
  [1744,'CECOVID4-CTI06-606-19','CMI - CIRURGIA GINECOLOGICA'],[1745,'CECOVID4-CTI06-606-20','CMI - CIRURGIA GINECOLOGICA'],
  [1748,'CECOVID4-CTI06-607-21','CMI - CIRURGIA GINECOLOGICA'],[1749,'CECOVID4-CTI06-607-22','CMI - CIRURGIA GINECOLOGICA'],
  [1750,'CECOVID4-CTI06-607-23','CMI - CIRURGIA GINECOLOGICA'],[1751,'CECOVID4-CTI06-607-24','CMI - CIRURGIA GINECOLOGICA'],
  [1752,'CECOVID4-CTI06-608-25','CMI - CIRURGIA GINECOLOGICA'],[1753,'CECOVID4-CTI06-608-26','CMI - CIRURGIA GINECOLOGICA'],
  [1754,'CECOVID4-CTI06-608-27','CMI - CIRURGIA GINECOLOGICA'],[1755,'CECOVID4-CTI06-608-28','CMI - CIRURGIA GINECOLOGICA'],
  [1756,'CECOVID4-CTI06-609-29','CMI - CIRURGIA GINECOLOGICA'],[1757,'CECOVID4-CTI06-609-30','CMI - CIRURGIA GINECOLOGICA'],
  [1724,'CG601-01','CMI - CIRURGIA GINECOLOGICA'],[1725,'CG601-02','CMI - CIRURGIA GINECOLOGICA'],
  [1727,'CG601-03','CMI - CIRURGIA GINECOLOGICA'],[1726,'CG601-03','CMI - CIRURGIA GINECOLOGICA'],
  [1728,'CG602-05','CMI - CIRURGIA GINECOLOGICA'],[1729,'CG602-06','CMI - CIRURGIA GINECOLOGICA'],[1730,'CG602-07','CMI - CIRURGIA GINECOLOGICA'],[1731,'CG602-08','CMI - CIRURGIA GINECOLOGICA'],
  [1732,'CG603-09','CMI - CIRURGIA GINECOLOGICA'],[1733,'CG603-10','CMI - CIRURGIA GINECOLOGICA'],[1734,'CG603-11','CMI - CIRURGIA GINECOLOGICA'],[1735,'CG603-12','CMI - CIRURGIA GINECOLOGICA'],
  [1738,'CG604-13','CMI - CIRURGIA GINECOLOGICA'],[1739,'CG604-14','CMI - CIRURGIA GINECOLOGICA'],[1740,'CG604-15','CMI - CIRURGIA GINECOLOGICA'],[1741,'CG604-16','CMI - CIRURGIA GINECOLOGICA'],
  // CMI - CTI PEDIATRICO
  [2264,'CTIP 01','CMI - CTI PEDIATRICO'],[2265,'CTIP 02','CMI - CTI PEDIATRICO'],[2266,'CTIP 03','CMI - CTI PEDIATRICO'],[2267,'CTIP 04','CMI - CTI PEDIATRICO'],
  [2268,'CTIP 05','CMI - CTI PEDIATRICO'],[2269,'CTIP 06','CMI - CTI PEDIATRICO'],[2286,'CTIP 07','CMI - CTI PEDIATRICO'],[2287,'CTIP 08','CMI - CTI PEDIATRICO'],
  [2288,'CTIP 09','CMI - CTI PEDIATRICO'],[2289,'CTIP 10','CMI - CTI PEDIATRICO'],
  // CMI - GAR ALOJAMENTO CONJUNTO
  [2290,'GAR603-09M','CMI - GAR ALOJAMENTO CONJUNTO'],[2291,'GAR603-09RN','CMI - GAR ALOJAMENTO CONJUNTO'],
  [2292,'GAR603-10M','CMI - GAR ALOJAMENTO CONJUNTO'],[2293,'GAR603-10RN','CMI - GAR ALOJAMENTO CONJUNTO'],
  [2294,'GAR603-11M','CMI - GAR ALOJAMENTO CONJUNTO'],[2295,'GAR603-11RN','CMI - GAR ALOJAMENTO CONJUNTO'],
  [2296,'GAR603-12M','CMI - GAR ALOJAMENTO CONJUNTO'],[2297,'GAR603-12RN','CMI - GAR ALOJAMENTO CONJUNTO'],
  // CMI - GESTAÇÃO DE ALTO RISCO
  [1971,'GAR 301 01 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2057,'GAR 301 01 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2181,'GAR 301 01 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1972,'GAR 301 02 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2182,'GAR 301 02 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2058,'GAR 301 02 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1973,'GAR 301 03 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2059,'GAR 301 03 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2226,'GAR 301 03 RN2 G2','CMI - GESTAÇÃO DE ALTO RISCO'],[2183,'GAR 301 03 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1974,'GAR 301 04 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2060,'GAR 301 04 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2184,'GAR 301 04 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1975,'GAR 302 05 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2185,'GAR 302 05 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2061,'GAR 302 05 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1976,'GAR 302 06 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2062,'GAR 302 06 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2186,'GAR 302 06 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1977,'GAR 302 07 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2063,'GAR 302 07 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2187,'GAR 302 07 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1978,'GAR 302 08 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2305,'GAR 302 08 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2064,'GAR 302 08 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1979,'GAR 303 09 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2065,'GAR 303 09 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2188,'GAR 303 09 RNG2','CMI - GESTAÇÃO DE ALTO RISCO'],[2189,'GAR 303 09 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1980,'GAR 303 10 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2190,'GAR 303 10 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2066,'GAR 303 10 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1981,'GAR 303 11 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2191,'GAR 303 11 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2067,'GAR 303 11 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1982,'GAR 303 12 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2192,'GAR 303 12 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2215,'GAR 303 12 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2068,'GAR 303 12 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1983,'GAR 304 13 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2069,'GAR 304 13 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2193,'GAR 304 13 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1984,'GAR 304 14 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2225,'GAR 304 14 RG','CMI - GESTAÇÃO DE ALTO RISCO'],[2070,'GAR 304 14 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2194,'GAR 304 14 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1985,'GAR 304 15 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2195,'GAR 304 15 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2071,'GAR 304 15 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1986,'GAR 304 16 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2196,'GAR 304 16 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2072,'GAR 304 16 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1987,'GAR 306 17 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2073,'GAR 306 17 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2197,'GAR 306 17 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1988,'GAR 306 18 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2074,'GAR 306 18 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2198,'GAR 306 18 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1989,'GAR 306 19 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2075,'GAR 306 19 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2199,'GAR 306 19 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1990,'GAR 306 20 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2200,'GAR 306 20 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2076,'GAR 306 20 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1991,'GAR 307 21 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2077,'GAR 307 21 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2201,'GAR 307 21 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1992,'GAR 307 22 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2078,'GAR 307 22 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2202,'GAR 307 22 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1993,'GAR 307 23 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2079,'GAR 307 23 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2203,'GAR 307 23 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1994,'GAR 307 24 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2204,'GAR 307 24 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2080,'GAR 307 24 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1995,'GAR 308 25 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2105,'GAR 308 25 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2205,'GAR 308 25 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1996,'GAR 308 26 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2106,'GAR 308 26 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2206,'GAR 308 26 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1997,'GAR 308 27 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2107,'GAR 308 27 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2207,'GAR 308 27 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1998,'GAR 308 28 M','CMI - GESTAÇÃO DE ALTO RISCO'],[2208,'GAR 308 28 RN','CMI - GESTAÇÃO DE ALTO RISCO'],[2108,'GAR 308 28 RR','CMI - GESTAÇÃO DE ALTO RISCO'],
  [1999,'GAR 309 29 ISO','CMI - GESTAÇÃO DE ALTO RISCO'],[2112,'GAR 309 29 RN ISO','CMI - GESTAÇÃO DE ALTO RISCO'],[2209,'GAR 309 29 RR ISO','CMI - GESTAÇÃO DE ALTO RISCO'],
  [2109,'GAR 310 30 ISO','CMI - GESTAÇÃO DE ALTO RISCO'],[2113,'GAR 310 30 RN ISO','CMI - GESTAÇÃO DE ALTO RISCO'],[2210,'GAR 310 30 RR ISO','CMI - GESTAÇÃO DE ALTO RISCO'],
  // CMI - UCINCA UNIDADE CANGURU
  [1941,'UCINCA 01','CMI - UCINCA UNIDADE CANGURU'],[1942,'UCINCA 02','CMI - UCINCA UNIDADE CANGURU'],
  [1946,'UCINCA 02 11','CMI - UCINCA UNIDADE CANGURU'],[1947,'UCINCA 02 12','CMI - UCINCA UNIDADE CANGURU'],
  [2213,'UCINCA 02 13','CMI - UCINCA UNIDADE CANGURU'],[2214,'UCINCA 02 14','CMI - UCINCA UNIDADE CANGURU'],
  [1943,'UCINCA 03','CMI - UCINCA UNIDADE CANGURU'],[1944,'UCINCA 04','CMI - UCINCA UNIDADE CANGURU'],[1945,'UCINCA 05','CMI - UCINCA UNIDADE CANGURU'],
  [2211,'UCINCA 06','CMI - UCINCA UNIDADE CANGURU'],[2212,'UCINCA 07','CMI - UCINCA UNIDADE CANGURU'],
  [1948,'UCINCA 08','CMI - UCINCA UNIDADE CANGURU'],[1949,'UCINCA 09 ISO','CMI - UCINCA UNIDADE CANGURU'],[1950,'UCINCA 10 ISO','CMI - UCINCA UNIDADE CANGURU'],
  // CMI - UCINCO INT CONVENCIONAIS
  [1951,'UCINCO 01','CMI - UCINCO INT CONVENCIONAIS'],[1952,'UCINCO 02','CMI - UCINCO INT CONVENCIONAIS'],[1953,'UCINCO 03','CMI - UCINCO INT CONVENCIONAIS'],
  [1954,'UCINCO 04','CMI - UCINCO INT CONVENCIONAIS'],[1955,'UCINCO 05','CMI - UCINCO INT CONVENCIONAIS'],[1956,'UCINCO 06','CMI - UCINCO INT CONVENCIONAIS'],
  [1957,'UCINCO 07','CMI - UCINCO INT CONVENCIONAIS'],[1958,'UCINCO 08','CMI - UCINCO INT CONVENCIONAIS'],[1959,'UCINCO 09','CMI - UCINCO INT CONVENCIONAIS'],
  [1960,'UCINCO 10','CMI - UCINCO INT CONVENCIONAIS'],[1961,'UCINCO 11','CMI - UCINCO INT CONVENCIONAIS'],[1962,'UCINCO 12','CMI - UCINCO INT CONVENCIONAIS'],
  [1963,'UCINCO 13','CMI - UCINCO INT CONVENCIONAIS'],[1964,'UCINCO 14','CMI - UCINCO INT CONVENCIONAIS'],[1965,'UCINCO 15','CMI - UCINCO INT CONVENCIONAIS'],
  [1966,'UCINCO 16','CMI - UCINCO INT CONVENCIONAIS'],[1967,'UCINCO 17','CMI - UCINCO INT CONVENCIONAIS'],[1968,'UCINCO 18','CMI - UCINCO INT CONVENCIONAIS'],
  [1969,'UCINCO 19','CMI - UCINCO INT CONVENCIONAIS'],[1970,'UCINCO 20','CMI - UCINCO INT CONVENCIONAIS'],
  // CMI - UDC PEDIATRICA
  [2278,'UDCP01','CMI - UDC PEDIATRICA'],[2279,'UDCP02','CMI - UDC PEDIATRICA'],[2280,'UDCP03','CMI - UDC PEDIATRICA'],
  [2281,'UTIPUR04','CMI - UDC PEDIATRICA'],[2282,'UTIPUR05','CMI - UDC PEDIATRICA'],[2283,'UTIPUR06','CMI - UDC PEDIATRICA'],
  [2284,'UTIPUR07','CMI - UDC PEDIATRICA'],[2285,'UTIPUR08','CMI - UDC PEDIATRICA'],
  // CMI - UNID RESP PEDIATRICA
  [2270,'CMIPUR01','CMI - UNID RESP PEDIATRICA'],[2271,'CMIPUR02','CMI - UNID RESP PEDIATRICA'],[2272,'CMIPUR03','CMI - UNID RESP PEDIATRICA'],
  [2273,'CMIPUR04','CMI - UNID RESP PEDIATRICA'],[2274,'CMIPUR05','CMI - UNID RESP PEDIATRICA'],[2275,'CMIPUR06','CMI - UNID RESP PEDIATRICA'],
  [2276,'CMIPUR07','CMI - UNID RESP PEDIATRICA'],[2277,'CMIPUR08','CMI - UNID RESP PEDIATRICA'],
  [2417,'CMIPUR09','CMI - UNID RESP PEDIATRICA'],[2418,'CMIPUR10','CMI - UNID RESP PEDIATRICA'],[2419,'CMIPUR11','CMI - UNID RESP PEDIATRICA'],
  [2420,'CMIPUR12','CMI - UNID RESP PEDIATRICA'],[2421,'CMIPUR13','CMI - UNID RESP PEDIATRICA'],[2422,'CMIPUR14','CMI - UNID RESP PEDIATRICA'],
  // CMI - UTIN NEO EXTREMO
  [2254,'UTIN 01','CMI - UTIN NEO EXTREMO'],[2255,'UTIN 02','CMI - UTIN NEO EXTREMO'],[2256,'UTIN 03','CMI - UTIN NEO EXTREMO'],
  [2257,'UTIN 04','CMI - UTIN NEO EXTREMO'],[2258,'UTIN 05','CMI - UTIN NEO EXTREMO'],[2259,'UTIN 06','CMI - UTIN NEO EXTREMO'],
  [2260,'UTIN 07','CMI - UTIN NEO EXTREMO'],[2261,'UTIN 08','CMI - UTIN NEO EXTREMO'],[2262,'UTIN 09','CMI - UTIN NEO EXTREMO'],[2263,'UTIN 10','CMI - UTIN NEO EXTREMO'],
  // CMI - UTIN NEONATOLOGIA
  [2252,'CTIP 01','CMI - UTIN NEONATOLOGIA'],[1932,'CTIP 02','CMI - UTIN NEONATOLOGIA'],[1931,'CTIP 02','CMI - UTIN NEONATOLOGIA'],
  [1933,'CTIP 03','CMI - UTIN NEONATOLOGIA'],[1934,'CTIP 04','CMI - UTIN NEONATOLOGIA'],[2111,'CTIP 04','CMI - UTIN NEONATOLOGIA'],
  [1935,'CTIP 05','CMI - UTIN NEONATOLOGIA'],[1936,'CTIP 06','CMI - UTIN NEONATOLOGIA'],[1937,'CTIP 07','CMI - UTIN NEONATOLOGIA'],
  [1938,'CTIP 08','CMI - UTIN NEONATOLOGIA'],[1939,'CTIP 09','CMI - UTIN NEONATOLOGIA'],[2253,'CTIP 09','CMI - UTIN NEONATOLOGIA'],
  [1940,'CTIP 10','CMI - UTIN NEONATOLOGIA'],[1929,'CTIP 11','CMI - UTIN NEONATOLOGIA'],[1919,'UTIN 01','CMI - UTIN NEONATOLOGIA'],
  [2250,'UTIN 11','CMI - UTIN NEONATOLOGIA'],[1922,'UTIN 12','CMI - UTIN NEONATOLOGIA'],[1923,'UTIN 13','CMI - UTIN NEONATOLOGIA'],
  [1924,'UTIN 14','CMI - UTIN NEONATOLOGIA'],[1925,'UTIN 15','CMI - UTIN NEONATOLOGIA'],[1926,'UTIN 16','CMI - UTIN NEONATOLOGIA'],
  [1927,'UTIN 17','CMI - UTIN NEONATOLOGIA'],[1928,'UTIN 18','CMI - UTIN NEONATOLOGIA'],[2251,'UTIN 19','CMI - UTIN NEONATOLOGIA'],[1930,'UTIN 20','CMI - UTIN NEONATOLOGIA']
];

// Leitos HPRB de exemplo (serão substituídos pelo Oracle quando conectado)
const LEITOS_HPRB_MOCK = [
  [3001,'ENF-101','HPRB - ENFERMARIA 1A'],[3002,'ENF-102','HPRB - ENFERMARIA 1A'],[3003,'ENF-103','HPRB - ENFERMARIA 1A'],
  [3004,'ENF-104','HPRB - ENFERMARIA 1A'],[3005,'ENF-201','HPRB - ENFERMARIA 2A'],[3006,'ENF-202','HPRB - ENFERMARIA 2A'],
  [3007,'PS-01','HPRB - PRONTO SOCORRO'],[3008,'PS-02','HPRB - PRONTO SOCORRO'],[3009,'PS-03','HPRB - PRONTO SOCORRO'],
  [3010,'MAT-01','HPRB - MATERNIDADE'],[3011,'MAT-02','HPRB - MATERNIDADE'],[3012,'CC-01','HPRB - CLINICA CIRURGICA']
];

// ─── Gerador de dados mock 100% sem repetição de nomes ───────────────────────
function gerarLeitosMock() {
  // Embaralha os nomes para distribuição aleatória mas determinística
  const nomesEmbaralhados = [...NOMES_UNICOS].sort(() => 0.5 - Math.sin(42));
  let nIdx = 0;
  let atd = 7432400;

  function proximoNome() {
    // Garante que nunca ultrapasse o array; se acabar, gera nome sintético único
    if (nIdx < nomesEmbaralhados.length) return nomesEmbaralhados[nIdx++];
    return `PACIENTE ANONIMO ${nIdx++}`;
  }

  // Padrão de ocupação por posição: 2 ocupados, 1 vago/higienização (ciclo de 3)
  function calcStatus(posicaoGlobal) {
    const r = posicaoGlobal % 3;
    if (r === 0) return 'livre';
    if (r === 7) return 'higienizacao'; // leitos múltiplos de 7 em higienização
    return 'ocupado';
  }

  const leitosCMI = LEITOS_REAIS_CMI_RAW.map(([cd, leito, unidade], idx) => {
    // Distribui: ~65% ocupados, ~20% livres, ~15% higienização
    let st;
    const mod = idx % 20;
    if (mod < 13)      st = 'ocupado';
    else if (mod < 17) st = 'livre';
    else               st = 'higienizacao';

    const isOcupado = (st === 'ocupado');
    return {
      cd_leito:       cd,
      leito:          leito,
      unidade:        unidade,
      hospital:       'CMI',
      cd_atendimento: isOcupado ? atd++    : null,
      nm_paciente:    isOcupado ? proximoNome() : null,
      dt_nascimento:  isOcupado ? gerarDataNasc(idx) : null,
      sexo:           isOcupado ? (idx % 2 === 0 ? 'F' : 'M') : null,
      status_leito:   st
    };
  });

  const leitosHPRB = LEITOS_HPRB_MOCK.map(([cd, leito, unidade], idx) => {
    const isOcupado = (idx % 3 !== 0);
    return {
      cd_leito:       cd,
      leito:          leito,
      unidade:        unidade,
      hospital:       'HPRB',
      cd_atendimento: isOcupado ? atd++    : null,
      nm_paciente:    isOcupado ? proximoNome() : null,
      dt_nascimento:  isOcupado ? gerarDataNasc(idx + 300) : null,
      sexo:           isOcupado ? (idx % 2 === 0 ? 'M' : 'F') : null,
      status_leito:   isOcupado ? 'ocupado' : 'livre'
    };
  });

  return [...leitosCMI, ...leitosHPRB];
}

function gerarDataNasc(seed) {
  const ano = 1950 + (seed * 7 % 50);
  const mes = String(1 + (seed * 3 % 12)).padStart(2, '0');
  const dia = String(1 + (seed * 11 % 28)).padStart(2, '0');
  return `${dia}/${mes}/${ano}`;
}

// ─── Agrega dados Oracle com fallback para mock ───────────────────────────────
async function getLeitos() {
  let oracleData = null;
  try {
    oracleData = await fetchLeitosOracle();
  } catch (e) {
    console.error('[ERRO BUSCA LEITOS]', e.message);
  }

  const base = (Array.isArray(oracleData) && oracleData.length > 0)
    ? oracleData
    : gerarLeitosMock();

  const dbData = readEventos();

  return base.map(l => ({
    ...l,
    hospital: l.hospital || resolverHospital(l.unidade),
    // Sobrepõe status manual apenas se foi alterado manualmente no painel
    ...(dbData.leitos[l.cd_leito] || dbData.leitos[l.leito] || {})
  }));
}

// ─── Endpoints ────────────────────────────────────────────────────────────────
app.get('/api/leitos', async (req, res) => {
  try {
    const leitos = await getLeitos();
    const dbData = readEventos();
    res.json({ leitos, historico: dbData.historico || [] });
  } catch (e) {
    console.error('[ERRO API /leitos]', e.message);
    res.json({ leitos: gerarLeitosMock(), historico: [] });
  }
});

app.post('/api/leitos/:leito/status', (req, res) => {
  const { leito } = req.params;
  const { status_leito, status_anterior, usuario } = req.body;
  const dbData = readEventos();

  dbData.leitos[leito] = {
    ...(dbData.leitos[leito] || {}),
    status_leito,
    atualizado_por: usuario || 'Operador',
    atualizado_em:  new Date().toISOString()
  };

  const hora = new Date().toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' });
  dbData.historico.unshift({
    id:              Date.now(),
    leito,
    status_anterior: status_anterior || '—',
    status_novo:     status_leito,
    usuario:         usuario || 'Operador',
    hora
  });
  if (dbData.historico.length > 60) dbData.historico = dbData.historico.slice(0, 60);

  writeEventos(dbData);
  broadcastSSE();
  res.json({ ok: true });
});

// ─── SSE — Tempo real para todos os clientes conectados ──────────────────────
const clientesSSE = [];

app.get('/api/leitos/stream', (req, res) => {
  res.set({ 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache', 'Connection': 'keep-alive' });
  res.flushHeaders();
  res.write('retry: 2000\n\n');
  clientesSSE.push(res);
  req.on('close', () => {
    const i = clientesSSE.indexOf(res);
    if (i >= 0) clientesSSE.splice(i, 1);
  });
});

function broadcastSSE() {
  const msg = `data: ${JSON.stringify({ tipo: 'atualizacao', em: new Date().toISOString() })}\n\n`;
  clientesSSE.forEach(r => { try { r.write(msg); } catch (_) {} });
}

// Heartbeat SSE a cada 10s para manter conexões vivas
setInterval(broadcastSSE, 10000);

// ─── Impressão ZPL ───────────────────────────────────────────────────────────
app.post('/api/imprimir/pulseira', async (req, res) => {
  try {
    const zpl = buildWristbandZPL(req.body);
    await printZPL(zpl, req.body.printer);
    res.json({ ok: true, zpl });
  } catch (e) {
    res.status(500).json({ erro: e.message });
  }
});

app.post('/api/imprimir/etiqueta', async (req, res) => {
  try {
    const zpl = buildLabelZPL(req.body);
    await printZPL(zpl, req.body.printer);
    res.json({ ok: true, zpl });
  } catch (e) {
    res.status(500).json({ erro: e.message });
  }
});

// ─── Start ────────────────────────────────────────────────────────────────────
app.listen(PORT, '0.0.0.0', () => {
  console.log(`\n✅ Painel de Leitos iniciado → http://localhost:${PORT}`);
  console.log(`   Leitos na base CMI: ${LEITOS_REAIS_CMI_RAW.length}`);
  console.log(`   Pool de nomes únicos: ${NOMES_UNICOS.length}`);
  console.log(`   Oracle: ${oracledb && process.env.DB_USER ? '🟢 Configurado' : '🟡 Modo demonstração'}\n`);
});